

name: Test Automation Workflow Selenium Cucumber

on:
  schedule:
    - cron: 30 03 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisHeadless=false

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test logs
          path: logs/

     
      - name: Upload HTML Report & Screenshots as Artifact
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test Reports and Screenhots
          path: Reports/

      - name: Test Execution Status
        if: always()
        run: echo "Test Execution Completed"

